name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Spécifiez la version de Node.js à utiliser

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Log in to Docker Hub
        run: echo "Mandeng123" | docker login -u "michelnyobe" --password-stdin

      - name: Build Docker image
        run: docker build -t todo-list-app .

      - name: Push Docker image
        run: |
          docker tag todo-list-app:latest michelnyobe/todo-list-app:latest
          docker push michelnyobe/todo-list-app:latest

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull michelnyobe/todo-list-app:latest"
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker stop todo-list-app || true"
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 80:80 --name todo-list-app michelnyobe/todo-list-app:latest"
          rm private_key.pem
